### 장바구니 담기
POST {{apiUrl}}/customers/me/carts
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "id": 1
}

### 장바구니 조회
GET {{apiUrl}}/customers/me/carts
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}
